version: '3.6'
services:
  auth:
    build:
      context: .
      dockerfile: GatewayDockerfile
    container_name: gateway
    networks:
      - backend
    expose:
      - 5000
    command: /usr/local/bin/gunicorn gateway.gateway:app -w 1 -t 90 -b 0.0.0.0:5000

#  web:
#    build:
#      context: .
#      dockerfile: FrontendDockerfile
#    depends_on:
#      - auth
#    ports:
#      - "8008:8008"

  nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    container_name: nginx  
    ports:
      - "7542:7542"
    networks:
      - backend
      - frontend
    depends_on:
      - auth

networks:
  frontend:
  backend: