version: '3.6'
services:
  auth:
    build:
      context: .
      dockerfile: AuthDockerfile
    container_name: auth
    networks:
      - backend
    expose:
      - 5000
    command: /usr/local/bin/gunicorn backend.auth.auth:app -w 1 -t 90 -b 0.0.0.0:5000

#  web:
#    build:
#      context: .
#      dockerfile: FrontendDockerfile
#    depends_on:
#      - auth
#    ports:
#      - "8008:8008"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7542:7542"
    networks:
      - backend
    depends_on:
      - auth

networks:
  frontend:
  backend: