version: '3.6'
services:
  gateway:
    build:
      context: .
      dockerfile: GatewayDockerfile
    container_name: gateway
    networks:
      - backend
    expose:
      - 5000
    depends_on:
      - redis
    command: /usr/local/bin/gunicorn gateway.gateway:app -w 1 -t 90 -b 0.0.0.0:5000

  web:
    build:
      context: .
      dockerfile: FrontendDockerfile
    container_name: web
    depends_on:
      - gateway
    networks:
      - frontend
    expose:
      - 8008
    command: yarn start

  nginx:
    build:
      context: .
      dockerfile: NginxDockerFile
    container_name: nginx  
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    depends_on:
      - gateway
      - web

  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always
    command: redis-server --appendonly yes

networks:
  frontend:
  backend:

volumes:
  redis_data: