version: '3.7'
services:
  web:
    build:
      context: ./services/web
    container_name: web
    environment:
        POSTGRES_CONN: "server=localhost;user=$POSTGRES_USER"
    env_file:
      - ./.env
    expose:
      - 5000
    depends_on:
      - redis
      - postgres
    command: ["web/wait-for-it.sh","${DB_HOST}:${DB_PORT}",
              "--",
              "/usr/local/bin/gunicorn", "web.app:app",
              "-w", "1", "-t", "90", "-b", "0.0.0.0:5000"
              ]

  task-executor:
    build:
      context: ./services/task-executor
    container_name: task-executor
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    command: python -m app

  data-registrator:
    build:
      context: ./services/data-registrator
    container_name: data-registrator
    env_file:
      - ./.env
    depends_on:
      - mosquitto
    command: python -m app

  data-analyzer:
    build:
      context: ./services/data-analyzer
    container_name: data-analyzer
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    command: celery -A common.resources.celery worker --loglevel=info

  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    depends_on:
      - web
    expose:
      - 8008
    command: sh -c "yarn build && yarn start-prod"

  nginx:
    image: nginx:latest
    container_name: nginx  
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/frontend/app/404.html:/etc/nginx/404.html
      - ./services/frontend/app/404.html:/usr/share/nginx/html/404.html
    depends_on:
      - web
      - data-registrator
      - task-executor
      - frontend

  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    restart: always
    command: redis-server --appendonly yes

  postgres:
    image: "postgres:11.2-alpine"
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./services/postgres/:/docker-entrypoint-initdb.d
#       - postgres-data:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf

#  mongo-db:
#    image: mongo:3.6
#    hostname: mongo-db
#    container_name: db-mongo
#    expose:
#      - "27017"
#    ports:
#      - "27017:27017"
#    networks:
#      - backend
#    command: --bind_ip_all --smallfiles
#    volumes:
#      - mongo-data:/data

volumes:
  redis_data:
  postgres-data:
  #mongo-data:
