version: '3.6'
services:
  gateway:
    build:
      context: .
      dockerfile: GatewayDockerfile
    container_name: gateway
    networks:
      - backend
    expose:
      - 5000
    command: /usr/local/bin/gunicorn gateway.gateway:app -w 1 -t 90 -b 0.0.0.0:5000
    depends_on:
      - redis

#  web:
#    build:
#      context: .
#      dockerfile: FrontendDockerfile
#    depends_on:
#      - gateway
#    ports:
#      - "8008:8008"

  nginx:
    build:
      context: .
      dockerfile: NginxDockerFile
    container_name: nginx  
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    depends_on:
      - gateway

  redis:
    image: redis:5.0.3-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - 6379
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:

volumes:
  redis_data: