version: '3.6'
services:
  web:
    build:
      context: ../..
      dockerfile: ../base/WebDockerfile
    container_name: web
    networks:
      - backend
    expose:
      - 5000
    depends_on:
      - redis
      - postgres
    environment:
      DEBUG: 'true'
    command: python -m web.app



  frontend:
    build:
      context: ../..
      dockerfile: ../../frontend/FrontendDockerfile
    container_name: frontend
    depends_on:
      - web
    networks:
      - frontend
    expose:
      - 8008
    command: yarn start